- id: ouro
  name: ouro
  description: "ouro is a Python package that checks your code for circular (cyclic) imports."
  entry: ouro
  language: python
  minimum_pre_commit_version: 2.9.1
  require_serial: true
  types_or: [python, pyi]
  pass_filenames: false
